### ISSUE TITLE
extract file to root directory？

### ISSUE THREAD

**Issue by w136111526** [pedrolcl/libq7zip#3]
Hello, I would like to write the 7Z file directly to the root directory, please ask how QFile should point to Sudo permission file to write, such as decompression directory is folder /opt

**Comment by pedrolcl** [comment]
Elevation of privileges has nothing to do with this library, because it is an operation not specific to a program doing file compress/decompress.  Any program writing files might want to do that. Think of a text editor: it can save text files only to locations where the user has permissions to write. Have you seen a Linux text editor calling sudo by itself?
Even the Qt Frameworks do not provide a cross-platform way to request elevation of privileges. Ask it to SO, if you can't find an answer of your liking: https://stackoverflow.com/questions/11714868/qt-make-program-ask-for-user-elevation-at-executionwindows
